.github/workflows/ci-cd-dev.yml, .github/workflows/dotnet.yml, .vscode/settings.json, devops/kustomize/base/database/kustomization.yaml, devops/kustomize/base/database/network-policy.yaml, devops/kustomize/base/tekton/imageStreams/api.yaml, devops/kustomize/base/tekton/imageStreams/app.yaml, devops/kustomize/base/tekton/imageStreams/db-migration.yaml, devops/kustomize/base/tekton/roles/role-bind.yaml, devops/kustomize/base/tekton/roles/role.yaml, devops/kustomize/base/tekton/taskruns/buildah.yaml, devops/kustomize/base/tekton/taskruns/db-migration.yaml, devops/kustomize/base/tekton/tasks/buildah.yaml, devops/kustomize/base/tekton/tasks/db-migration.yaml, devops/sysdig/Monitoring.md, devops/sysdig/tno-sysdig-access.yaml, do, scripts/docker.sh, scripts/oc.sh, scripts/setup.sh, scripts/test.sh, src/libs/.dockerignore, src/libs/Dockerfile
I was hoping to have automated pipelines, however it doesn't appear Emerald cluster supports this easily.  I've instead created local scripts that automate the build/deploy for the various components.
- Emerald cluster does not allow external ingess, which means webhooks and GitHub Actions cannot interact with Openshift
- I was unable to figure out how to push images to Artifactory image registry directly, however I was able to figure out how to push the bcgov GitHub image registry
- Openshift ImageStreams can be setup with a 15 minute schedule where they check if an image has been updated in Artifactory, or GitHub.
- With schedule ImageStreams it will update the API or APP automatically when new images are push up
- However, current it isn't possible to start a DB migration …
=> HOSTSD-146 Add CI/CD

src/dashboard/src/components/charts/doughnut/IDoughnutStats.ts, src/dashboard/src/components/charts/doughnut/allOrganizations/AllOrganizations.tsx, src/dashboard/src/components/charts/doughnut/allOrganizations/defaultData.ts, src/dashboard/src/components/charts/doughnut/allOrganizations/hooks/generateDoughnutChart.ts, src/dashboard/src/components/charts/doughnut/allOrganizations/hooks/index.ts, src/dashboard/src/components/charts/doughnut/allOrganizations/hooks/useAllOrganizationsDoughnutChart.ts, src/dashboard/src/components/charts/doughnut/index.ts, src/dashboard/src/components/charts/doughnut/totalStorage/TotalStorage.tsx, src/dashboard/src/components/charts/doughnut/totalStorage/defaultData.ts, src/dashboard/src/components/charts/doughnut/totalStorage/hooks/generateDoughnutChart.ts, src/dashboard/src/components/charts/doughnut/totalStorage/hooks/index.ts, src/dashboard/src/components/charts/doughnut/totalStorage/hooks/useTotalStorageDoughnutChart.ts, src/dashboard/src/components/charts/hooks/index.ts, src/dashboard/src/components/charts/index.ts
Hooked up the Total Storage Allocation doughnut chart.  This chart uses the dashboard state store.
=> HOSTSD-201 Add total storage chart

src/libs/core/HSB.Core.csproj
Cannot upgrade `System.IdentityModel.Tokens.Jwt` to 7 presently, despite the security alert.
=> Rollback dependency version

src/api/Areas/Dashboard/Controllers/OperatingSystemItemController.cs, src/api/Areas/Dashboard/Controllers/OrganizationController.cs, src/api/Areas/Dashboard/Controllers/ServerItemController.cs, src/api/Areas/Dashboard/Controllers/TenantController.cs, src/api/Program.cs, src/libs/dal/Services/IOrganizationService.cs, src/libs/dal/Services/OrganizationService.cs, src/libs/dal/Services/TenantService.cs, src/libs/models/Filters/OrganizationFilter.cs
Fixed issue where no organizations would be returned for client user with tenant.  Also removed caching as it was causing issues testing different accounts.
=> A few fixes for client users

src/api/Areas/Dashboard/Controllers/FileSystemItemController.cs, src/dashboard/src/app/client/dashboard/page.tsx, src/dashboard/src/components/charts/bar/segmentedBarChart/IVolumeData.ts, src/dashboard/src/components/charts/bar/segmentedBarChart/SegmentedBarChart.module.scss, src/dashboard/src/components/charts/bar/segmentedBarChart/SegmentedBarChart.tsx, src/dashboard/src/components/charts/bar/segmentedBarChart/defaultData.ts, src/dashboard/src/components/charts/bar/segmentedBarChart/defaultOptions.ts, src/dashboard/src/components/charts/bar/segmentedBarChart/useStorageTrends.ts, src/dashboard/src/components/charts/bar/segmentedBarChart/utils/extractVolumeName.ts, src/dashboard/src/components/charts/bar/segmentedBarChart/utils/index.ts, src/dashboard/src/components/charts/hooks/index.ts, src/dashboard/src/components/charts/hooks/useStorageHistoryDateRange.ts, src/dashboard/src/components/charts/storageTrends/useStorageTrends.ts, src/dashboard/src/hooks/dashboard/useDashboardFileSystemHistoryItems.ts, src/libs/dal/Migrations/0.0.0/Up/PostUp/04-FindFileSystemHistoryItemsByMonth.sql
This one was complicated.  Many of our servers have more than 3 mapped volumes, and many have no mapped volumes.  I have updated the Storage Trends by Drive to display how many total drives are on the server.
There are many drives with 0 storage, which could be a data issue, or simple some of these drives are not relevant (i.e. System).
I've extracted the last portion of their mapped name for the label.
=> HOSTSD-203 Add storage trends by drive

src/dashboard/src/app/client/servers/page.tsx, src/dashboard/src/components/charts/allocationTable/AllocationTable.module.scss, src/dashboard/src/components/charts/allocationTable/AllocationTable.tsx, src/dashboard/src/components/charts/allocationTable/ITableRowData.ts, src/dashboard/src/components/charts/allocationTable/TableRow.tsx, src/dashboard/src/components/charts/allocationTable/defaultData.ts, src/dashboard/src/components/charts/allocationTable/hooks/useAllocationByOS.ts, src/dashboard/src/components/charts/bar/allocationByOS/AllocationByOS.tsx, src/dashboard/src/components/charts/bar/allocationByOS/defaultData.ts, src/dashboard/src/components/charts/bar/allocationByOS/utils/groupByOS.ts, src/dashboard/src/components/charts/bar/allocationByStorageVolume/AllocationByStorageVolume.module.scss, src/dashboard/src/components/charts/bar/allocationByStorageVolume/AllocationByStorageVolume.tsx, src/dashboard/src/components/charts/bar/allocationByStorageVolume/BarChart.tsx, src/dashboard/src/components/charts/bar/allocationByVolume/AllocationByVolume.tsx, src/dashboard/src/components/charts/bar/allocationByVolume/defaultData.ts, src/dashboard/src/components/charts/bar/smallBar/BarRow.tsx, src/dashboard/src/components/charts/bar/smallBar/IBarChartData.ts, src/dashboard/src/components/charts/bar/smallBar/IBarChartRowData.ts, src/dashboard/src/components/charts/bar/smallBar/SmallBarChart.module.scss, src/dashboard/src/components/charts/bar/smallBar/SmallBarChart.tsx, src/dashboard/src/components/dashboard/Dashboard.tsx, src/dashboard/src/components/dashboard/index.ts, src/dashboard/src/components/dashboard/useDashboardFilter.ts, src/dashboard/src/components/filter/Filter.tsx
Client users now have the various dashboard views and the All Servers page.
I have also updated charts that had links (organization, operating system, server) to update the filter when they are clicked.  I think I'll need to go back and update this functionality to support the back button however.
=> HOSTSD-229 Client pages

src/dashboard/src/app/hsb/admin/users/Users.module.scss, src/dashboard/src/app/hsb/admin/users/page.tsx, src/dashboard/src/components/table/ITableAddNewProps.ts, src/dashboard/src/components/table/Table.module.scss, src/dashboard/src/components/table/Table.tsx
Adding ability to add rows to the table on hsb/admin/users page so that users can input information to add new users.
Added new 'addNew' section to the table component by copying how the table 'header' is conditionally added.
Functionality to add info to new users is still needed, including functionality for the popups for Role, Tenant, and Organization.
=> HOSTSD-288 - UI: add new users for hsb/admin/users page

src/dashboard/src/app/client/admin/users/page.tsx, src/dashboard/src/components/dashboard/Dashboard.tsx, src/dashboard/src/components/filter/Filter.tsx
Fixing issues in the Client Organization Admin page for user management.  An Organization Admin will only be able to add/remove the `organization-admin` role, and tenants and organizations they belong to.
=> HOSTSD-292 Fix Organization Admin

src/dashboard/src/styles/_globals.scss
Hiding export to excel button for all charts on dashboard so users can focus more on dashboard functionality and usage.
Can be unhidden at any time.
=> No ticket - hiding excel button for all charts

src/dashboard/src/app/client/servers/page.tsx, src/dashboard/src/app/hsb/servers/page.tsx, src/dashboard/src/components/dashboard/Dashboard.tsx
This should fix two bugs.
- All Servers page links were not working due to regression issue introduced today (to fix another bug)
- When an OS is selected in the filter it will no longer show the All Organization Allocation table chart
=> HOSTSD-275 Fix dashboard

src/dashboard/src/components/breadcrumbs/Breadcrumbs.tsx, src/dashboard/src/components/charts/allocationTable/AllocationTable.module.scss, src/dashboard/src/components/charts/allocationTable/AllocationTable.tsx, src/dashboard/src/components/charts/doughnut/totalStorage/TotalStorage.module.scss, src/dashboard/src/components/header/Message.tsx
- Updating breadcrumbs and header messaging so they only update after the dashboard has been updated (after 'update' button in Filter is clicked).  Using `useDashboardStore` instead of `useFilteredStore`.
- Server charts: Adding OS name to chart when looking at single OS page.  Adding totals for allocated and unused space at the top of the charts.
- Including a few small style fixes
=> HOSTSD-271 - Updating Breadcrumbs and adding totals to server charts

EMERALD.md, README.md, devops/kustomize/base/tekton/tasks/data-service.yaml
Added documentation to help future developers understand how to spin up new environments.  It's very simple, but it gives examples and everything exists as Infrastructure as Code.
=> HOSTSD-306 Documentation

src/dashboard/src/components/charts/storageTrends/StorageTrendsChart.tsx, src/dashboard/src/components/charts/storageTrends/hooks/index.ts, src/dashboard/src/components/charts/storageTrends/hooks/useStorageTrendsData.ts, src/data-service/DataService.cs, src/libs/dal/Services/ServerItemService.cs, src/libs/models/ServerItemModel.cs
Resolved an issue which was resulting in storage trends missing data.
=> HOSTSD-246 Fix Data Service

src/api/Areas/Services/Controllers/OrganizationController.cs, src/data-service/Config/ServiceOptions.cs, src/data-service/DataService.cs, src/data-service/Helpers/HsbApiService.cs, src/data-service/Helpers/IHsbApiService.cs, src/libs/dal/Services/IOrganizationService.cs, src/libs/dal/Services/OrganizationService.cs
The Data Service will now delete organizations that don't have any servers at the end of the process.
It cannot be done during because we don't know which organizations do not have servers until the end.
=> HOSTSD-246 Enhance Data Service

devops/kustomize/base/api/network-policy.yaml, devops/kustomize/base/database/network-policy.yaml, devops/kustomize/base/jobs/data-service.yaml, devops/kustomize/base/jobs/kustomization.yaml, devops/kustomize/overlays/dev/jobs/kustomization.yaml, devops/kustomize/overlays/dev/kustomization.yaml, devops/kustomize/overlays/prod/api/kustomization.yaml, devops/kustomize/overlays/prod/app/kustomization.yaml, devops/kustomize/overlays/prod/data-service/kustomization.yaml, devops/kustomize/overlays/prod/database/kustomization.yaml, devops/kustomize/overlays/prod/jobs/kustomization.yaml, devops/kustomize/overlays/prod/kustomization.yaml, devops/kustomize/overlays/secrets/prod/kustomization.yaml, devops/kustomize/overlays/test/jobs/kustomization.yaml, src/api/Areas/Admin/Controllers/UserController.cs, src/dashboard/src/components/auth/AuthState.tsx, src/data-service/DataService.cs
Configuration and setup of PROD.
=> HOSTSD-305 Configure PROD

src/dashboard/src/app/login/Login.module.scss, src/dashboard/src/components/charts/doughnut/allOrganizations/AllOrganizations.module.scss, src/dashboard/src/components/charts/line/LineChart.module.scss, src/dashboard/src/components/charts/line/LineChart.tsx, src/dashboard/src/components/charts/storageTrends/StorageTrendsChart.module.scss, src/dashboard/src/components/charts/storageTrends/StorageTrendsChart.tsx, src/dashboard/src/components/filter/Filter.module.scss, src/dashboard/src/components/filter/Filter.tsx, src/dashboard/src/components/header/Header.module.scss, src/dashboard/src/styles/_variables.scss
- Adding responsive styles for filter, new breakpoint at 975px width.  Dropdowns and buttons stack.  Also cleaned up header responsive styles.
- Filter reset button: making the button appear only after selections have been made in the dropdowns.
- Storage Trends chart: fixing bug where the chart grows taller until the data is rendered. (314)
=> HOSTSD-217, 262, 314 - Adding responsive styles for filter

src/api/Areas/Dashboard/Controllers/ServerItemController.cs, src/api/Helpers/IXlsExporter.cs, src/api/Helpers/XlsExporter.cs, src/dashboard/src/app/api/dashboard/server-items/history/export/route.ts, src/dashboard/src/app/client/servers/page.tsx, src/dashboard/src/app/hsb/servers/page.tsx, src/dashboard/src/components/charts/allocationTable/AllocationTable.tsx, src/dashboard/src/components/charts/bar/allocationByOS/AllocationByOS.tsx, src/dashboard/src/components/charts/bar/allocationByStorageVolume/AllocationByStorageVolume.tsx, src/dashboard/src/components/charts/bar/segmentedBarChart/SegmentedBarChart.tsx, src/dashboard/src/components/charts/bar/smallBar/SmallBarChart.tsx, src/dashboard/src/components/charts/doughnut/allOrganizations/AllOrganizations.tsx, src/dashboard/src/components/charts/line/LineChart.tsx, src/dashboard/src/components/charts/storageTrends/StorageTrendsChart.tsx, src/dashboard/src/components/dashboard/Dashboard.tsx, src/dashboard/src/hooks/api/interfaces/IServerItemFilter.ts, src/dashboard/src/hooks/api/useApiServerItems.ts, src/dashboard/src/hooks/index.ts, src/dashboard/src/hooks/useDownload.ts, src/dashboard/src/styles/_globals.scss, src/libs/dal/Services/IServerHistoryItemService.cs, src/libs/dal/Services/IServerItemService.cs, src/libs/dal/Services/ServerHistoryItemService.cs, src/libs/dal/Services/ServerItemService.cs, src/libs/models/Filters/ServerItemFilter.cs
Added endpoints to download the server data as an Excel document.  We can include more information about each server if we want, but presently I am only including the basic information.
Storage Trends downloads the data for each month.
=> HOSTSD-237 Export to Excel

src/dashboard/src/app/client/servers/page.tsx, src/dashboard/src/app/hsb/servers/page.tsx, src/dashboard/src/components/dashboard/Dashboard.tsx
Adding React Toast messages for excel export loading state - `toast.loading`: "Generating Excel document...", and `toast.success`: "Excel document has been downloaded successfully."
=> HOSTSD-315 - adding toast messages for excel export functions

src/dashboard/src/components/dashboard/Dashboard.tsx, src/dashboard/src/components/filter/FilteredOrganizations.tsx, src/dashboard/src/components/filter/FilteredTenants.tsx
If a user belongs to a tenant that owns more than one organization, the All Storage chart should display all organizations they have access to.
If the user only has access to a single tenant or a single organization hide those dropdown filter options.
=> HOSTSD-295 Fix dashboard and filter

src/dashboard/src/components/filter/Filter.module.scss, src/dashboard/src/components/forms/select/Select.module.scss
- Adjusted the filter dropdown z-index so that they are no longer covered by the chart loading overlays.
- Adjusted the width for the filter dropdowns so they take up the empty space if one is not displayed.
=> HOSTSD-317 - fixing dropdown covered by loading overlay bug

src/data-service/Helpers/ServiceNowApiService.cs
The Data Service will now treat a 404 error as a 204 so that it doesn't error out when an item no longer exists.
=> HOSTSD-310 Update Data Service

src/dashboard/src/components/dashboard/Dashboard.tsx
The Storage Trends chart aspect ratio was off when navigating back to the All Organizations view - the chart was too short because it was keeping the longer aspect ratio from the larger size of the chart on other views.
To fix this, it seems the chart needs to be rendered separately for each size depending on which view the user is looking at.
=> HOSTSD-293 - fix for storage trends chart aspect ratio bug

README.md, src/dashboard/src/components/forms/select/FilterDropdown.tsx
Fixed issue with dropdown state.
=> HOSTSD-320 Fix filter dropdown

src/dashboard/src/components/dashboard/Dashboard.tsx, src/dashboard/src/hooks/filter/useFilteredFileSystemItems.ts, src/dashboard/src/hooks/filter/useFilteredOperatingSystemItems.ts, src/dashboard/src/hooks/filter/useFilteredOrganizations.ts, src/dashboard/src/hooks/filter/useFilteredServerItems.ts, src/dashboard/src/hooks/filter/useFilteredTenants.ts, src/dashboard/src/store/useFilteredStore.ts
Fixed state issue when loading file system items.
=> HOSTSD-319 Fix Drive Space Loading

devops/kustomize/base/app/config-map.yaml, devops/kustomize/base/app/route.yaml, devops/kustomize/overlays/dev/app/kustomization.yaml, devops/kustomize/overlays/dev/kustomization.yaml, devops/kustomize/overlays/prod/app/kustomization.yaml, devops/kustomize/overlays/prod/kustomization.yaml, devops/kustomize/overlays/test/app/kustomization.yaml, devops/kustomize/overlays/test/kustomization.yaml
Updating the kustomize base and overlays to add support for the vanity TLS URL.
Updating the configuration to use the vanity TLS URL instead of the default apps domain.
=> Adding support for STMS domains

src/api-css/Dockerfile, src/api-css/HSB.CSS.API.csproj, src/api/Dockerfile, src/api/HSB.API.csproj, src/data-service/Dockerfile, src/data-service/HSB.DataService.csproj, src/libs/ches/HSB.Ches.csproj, src/libs/core/HSB.Core.csproj, src/libs/css/HSB.CSS.csproj, src/libs/dal/HSB.DAL.csproj, src/libs/entities/HSB.Entities.csproj, src/libs/keycloak/HSB.Keycloak.csproj, src/libs/models/HSB.Models.csproj
Upgraded each library and tested to confirm everything continues to work correctly.  I had some issues, but was able to update all packages except LinqKit.  I am still working through the library publisher to debug why we can't upgrade to the latest library.
Upgrade enhancements listed here - https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8/overview
.NET9.0 will most likely be coming out this Fall.
=> Upgrade .Net7.0 to 8.0

src/api/Areas/Admin/Controllers/GroupController.cs, src/api/Areas/Admin/Controllers/OrganizationController.cs, src/api/Areas/Admin/Controllers/RoleController.cs, src/api/Areas/Admin/Controllers/TenantController.cs, src/api/Areas/Admin/Controllers/UserController.cs, src/libs/dal/Services/IOrganizationService.cs, src/libs/dal/Services/ITenantService.cs, src/libs/dal/Services/OrganizationService.cs, src/libs/dal/Services/TenantService.cs, src/libs/models/Admin/OrganizationModel.cs, src/libs/models/Admin/TenantModel.cs
Update code and improve performance.  Debugged issue related to a 401 error with cached data.
=> Improve Performance

.vscode/settings.json, README.md, devops/kustomize/base/data-service/config-map.yaml, devops/kustomize/overlays/dev/data-service/kustomization.yaml, devops/kustomize/overlays/dev/kustomization.yaml, devops/kustomize/overlays/prod/data-service/kustomization.yaml, devops/kustomize/overlays/prod/kustomization.yaml, devops/kustomize/overlays/test/data-service/kustomization.yaml, devops/kustomize/overlays/test/kustomization.yaml, scripts/db-migration.sh, scripts/do-args.sh, scripts/help.sh, scripts/oc.sh, scripts/setup.sh, scripts/variables.sh, src/api/.gitignore, src/api/Dockerfile, src/api/Keycloak/CssHelper.cs, src/dashboard/Dockerfile.prod, src/dashboard/src/app/login/page.tsx, src/data-service/Dockerfile, src/data-service/Helpers/HsbApiService.cs, src/data-service/Helpers/ServiceNowApiService.cs
This is mainly to test GitHub Actions.
Changes:
* Update documentation to tell Mac users to use `gnu-getopt`.
* Add a log message to the API.
* Tweak text on landing page.
=> Deployment tweaks
