bcgov/hsb-dashboard

README.md
devops/kustomize/base/api/route.yaml
devops/kustomize/base/app/config-map.yaml
devops/kustomize/base/app/network-policy.yaml
devops/kustomize/base/app/route.yaml
devops/kustomize/overlays/dev/api/kustomization.yaml
devops/kustomize/overlays/dev/app/kustomization.yaml
devops/kustomize/overlays/dev/kustomization.yaml
do
scripts/oc.sh
scripts/setup.sh

Resolve issues with DEV environment related to routes and Keycloak authentication.
Cleaned up scripts to setup local environment.
Add scripts to manually build and deploy the solution to Openshift.  I still need to figure out how to hook up GitHub Actions with Emerald realm.

HOSTSD-140 Setup DEV

---

README.md
devops/kustomize/tools/build/api.yaml
devops/kustomize/tools/build/app.yaml
devops/kustomize/tools/build/db-migration.yaml
do
keycloak/config/realm-export.json
scripts/npm.sh

Adding additional scheduled ImageStreams for dev and test.
Added new script `./do npm-install` so that we don't have to navigate to the directory manually.

Testing auto ci/cd pipeline

---

src/dashboard/src/app/api/auth/authOptions.ts
src/dashboard/src/app/api/auth/refreshToken.ts
src/dashboard/src/components/auth/AuthState.tsx
src/dashboard/src/hooks/useAuth.ts

Provided a way to fake authentication and authorization through the `env` file.  This is to help Will continue working until he can fix his Docker Desktop issues.
Add the following to your `.env` file and `./do refresh app`.
```env
NEXT_PUBLIC_AUTH_STATUS=authenticated
NEXT_PUBLIC_AUTH_ROLES=hsb,system-admin
```

Provide authentication workaround

---

src/dashboard/src/app/style-guide/page.tsx
src/dashboard/src/app/styles/_globals.scss
src/dashboard/src/app/styles/_variables.scss
src/dashboard/src/components/buttons/Button.tsx
src/dashboard/src/components/filter/Filter.module.scss
src/dashboard/src/components/filter/Filter.tsx
src/dashboard/src/components/filter/index.ts
src/dashboard/src/components/header/Header.module.scss
src/dashboard/src/components/header/Header.tsx

Added the filter component for the dashboard view.
Updated some logic for showing/hiding sub-navs for the header.

HOSTSD-170 - Filter component

---

src/dashboard/src/app/globals.css
src/dashboard/src/app/login/Login.module.scss
src/dashboard/src/app/login/page.tsx
src/dashboard/src/app/styles/_globals.scss
src/dashboard/src/app/styles/_variables.scss
src/dashboard/src/app/welcome/Welcome.module.scss
src/dashboard/src/app/welcome/page.tsx
src/dashboard/src/components/buttons/Button.tsx
src/dashboard/src/components/header/Header.module.scss
src/dashboard/src/components/header/Header.tsx

Adding styling and structure for login and welcome pages.  
Added logic to header so that only the top portion shows on these pages.

HOSTSD-168 - adding styling for login and welcome pages

---

devops/kustomize/base/app/network-policy.yaml
src/dashboard/Dockerfile.prod
src/dashboard/src/app/api/auth/userinfo/route.ts
src/dashboard/src/app/hsb/admin/users/page.tsx
src/dashboard/src/components/auth/AuthState.tsx
src/dashboard/src/hooks/useApi.ts

When a user signs in their account will be activated automatically.  Then they will show up in the user administration without any roles.

HOSTSD-91 Activate user

---

devops/kustomize/base/api/network-policy.yaml
scripts/database.sh
scripts/docker.sh
src/api/Areas/Services/Controllers/DataSyncController.cs
src/dashboard/package-lock.json
src/dashboard/package.json
src/dashboard/src/app/hsb/admin/users/page.tsx
src/dashboard/src/components/auth/AuthState.tsx
src/dashboard/src/hooks/index.ts
src/dashboard/src/hooks/useApp.ts
src/data-service/Config/DataSyncOptions.cs
src/data-service/Config/HsbApiEndpointOptions.cs
src/data-service/Config/ServiceOptions.cs
src/data-service/DataService.cs
src/data-service/Helpers/HsbApiService.cs
src/data-service/Helpers/IHsbApiService.cs
src/libs/dal/Configuration/DataSyncConfiguration.cs
src/libs/dal/Migrations/1.0.0/Up/PostUp/00-DataSync.sql
src/libs/dal/Migrations/20231219205144_1.0.0.Designer.cs
src/libs/dal/Migrations/20231219205144_1.0.0.cs
src/libs/dal/Services/DataSyncService.cs
src/libs/dal/Services/IDataSyncService.cs
src/libs/entities/DataSync.cs
src/libs/entities/ServiceNowDataType.cs
src/libs/models/CommonAuditableModel`.cs
src/libs/models/DataSyncModel.cs
src/libs/models/SortableAuditableModel`.cs

Added `1.0.0` DB migration to support a new DataSync table.
Data Service now has a way to pick up where it left off.
Fixed `bash do db-add` script.

HOSTSD-121 Apply roles & HOSTSD-159 Enhance Data Service

---

src/dashboard/src/components/charts/allOrgDonut/AllOrgDonutChart.tsx
src/dashboard/src/components/charts/allOrgDonut/defaultData.ts
src/dashboard/src/components/charts/allOrgDonut/updateData.ts
src/dashboard/src/components/charts/allOrgDonut/useDonutChart.ts
src/dashboard/src/components/filter/Filter.tsx
src/dashboard/src/utils/convertToStorageSize.ts

Fixing data presentation issues.
We have the majority of API endpoints now.
Still need to improve the filter experience and implement the Update button.  Currently it updates the dashboard as the user selects values.

HOSTSD-189 Add file system endpoints

---

database/Dockerfile
src/api/Dockerfile
src/dashboard/src/app/hsb/dashboard/page.tsx
src/dashboard/src/components/charts/bar/index.ts
src/dashboard/src/components/charts/bar/segmentedBarChart/SegmentedBarChart.module.scss
src/dashboard/src/components/charts/bar/segmentedBarChart/SegmentedBarChart.tsx
src/dashboard/src/components/charts/bar/segmentedBarChart/defaultData.ts
src/dashboard/src/components/charts/bar/segmentedBarChart/index.ts
src/dashboard/src/components/charts/doughnut/allOrganizations/AllOrganizations.module.scss
src/data-service/Dockerfile

Adding segmented bar chart for drive storage and default data.
Some Dockerfile changes are included, these can be rolled back before merging if necessary.

HOSTSD-182 - Adding segmented bar chart for drive storage

---

src/dashboard/src/app/hsb/admin/users/Users.module.scss
src/dashboard/src/app/hsb/admin/users/page.tsx
src/dashboard/src/components/forms/select/Select.module.scss
src/dashboard/src/components/forms/select/Select.tsx
src/dashboard/src/components/header/Header.module.scss
src/dashboard/src/components/header/Header.tsx
src/dashboard/src/components/info/Info.module.scss
src/dashboard/src/components/sheet/Sheet.module.scss
src/dashboard/src/components/table/Table.module.scss

Adding styles for HSB admin - users admin page.
Mostly added styles and custom behaviour for multi-select dropdown.

HOSTSD-225 - HSB Admin - Users Admin page

---

src/dashboard/src/app/client/servers/page.tsx
src/dashboard/src/components/dashboard/Dashboard.tsx
src/dashboard/src/components/filter/Filter.tsx
src/dashboard/src/components/filter/hooks/useUrlParamsUpdateKey.ts
src/libs/dal/Services/ServerItemService.cs

Fixed various issues related to URL query parameter navigation which would lead to infinite loops.
Fixed issue on All Server page so that operating system information is displayed.
Fixed issue where servers without tenants were being incorrectly returned for client users.
Fixed issue on dashboard where the all organization chart was being displayed when it shouldn't.

HOSTSD-209 Fix URL navigation

---

src/dashboard/src/app/client/servers/page.tsx
src/dashboard/src/app/hsb/servers/page.tsx
src/dashboard/src/components/filter/Filter.tsx
src/libs/models/Filters/ServerHistoryItemFilter.cs
src/libs/models/Filters/ServerItemFilter.cs

Resolved a number of filter issues that occur depending on the path the user takes.

Fixes for filter

---

src/dashboard/src/app/client/servers/page.tsx
src/dashboard/src/app/hsb/admin/users/page.tsx
src/dashboard/src/app/hsb/servers/page.tsx
src/dashboard/src/components/charts/allocationTable/AllocationTable.module.scss
src/dashboard/src/components/charts/allocationTable/AllocationTable.tsx
src/dashboard/src/components/charts/allocationTable/TableRow.tsx
src/dashboard/src/components/confirmPopup/ConfirmPopup.module.scss
src/dashboard/src/components/confirmPopup/ConfirmPopup.tsx
src/dashboard/src/components/confirmPopup/index.ts
src/dashboard/src/components/header/Header.tsx
src/dashboard/src/components/index.ts

Added new component for the confirm navigation popup to be used on all admin pages.
Fixed styling for table on all server page.

HOSTSD-226, 183 - Added admin confirmation popup and fixed server page styling

---

.github/workflows/ci-cd-dev.yml
.github/workflows/dotnet.yml
devops/kustomize/base/api/deploy.yaml
devops/kustomize/base/data-service/cron-job.yaml
devops/kustomize/base/data-service/kustomization.yaml
devops/kustomize/tools/build/data-service.yaml
src/dashboard/src/components/filter/FilteredTenants.tsx

Adding Data Service to the CI/CD.  It should build and deploy the image to Artifactory.
- Fix Filter Tenant bug
- Update CI/CD
- Fix API environment configuration to resolve CSS API proxy rule

HOSTSD-235 Deploy Data Service

---

src/dashboard/src/components/buttons/Button.module.scss
src/dashboard/src/components/charts/allocationTable/AllocationTable.module.scss
src/dashboard/src/components/charts/allocationTable/AllocationTable.tsx
src/dashboard/src/components/charts/bar/allocationByOS/AllocationByOS.tsx
src/dashboard/src/components/charts/bar/allocationByStorageVolume/AllocationByStorageVolume.tsx
src/dashboard/src/components/charts/bar/allocationByVolume/AllocationByVolume.tsx
src/dashboard/src/components/charts/bar/segmentedBarChart/SegmentedBarChart.tsx
src/dashboard/src/components/charts/bar/smallBar/SmallBarChart.tsx
src/dashboard/src/components/charts/doughnut/allOrganizations/AllOrganizations.tsx
src/dashboard/src/components/charts/doughnut/totalStorage/TotalStorage.tsx
src/dashboard/src/components/charts/index.ts
src/dashboard/src/components/charts/line/LineChart.tsx
src/dashboard/src/components/charts/loadingAnimation/LoadingAnimation.module.scss
src/dashboard/src/components/charts/loadingAnimation/LoadingAnimation.tsx
src/dashboard/src/components/charts/loadingAnimation/index.ts
src/dashboard/src/components/charts/storageTrends/StorageTrendsChart.tsx
src/dashboard/src/components/dashboard/Dashboard.tsx
src/dashboard/src/components/forms/select/Select.module.scss

- Adding loading component to all charts
- Updating Loading state for filter dropdowns and button
Although the loading state and component are added to each chart, some logic for making the loading state appear at the right time is still needed.

HOSTSD-243 - adding loading component to all charts

---

src/dashboard/src/app/client/admin/users/page.tsx
src/dashboard/src/app/client/dashboard/page.tsx
src/dashboard/src/app/client/servers/page.tsx
src/dashboard/src/app/hsb/admin/organizations/page.tsx
src/dashboard/src/app/hsb/admin/users/page.tsx
src/dashboard/src/app/hsb/dashboard/page.tsx
src/dashboard/src/app/hsb/servers/page.tsx
src/dashboard/src/app/page.tsx
src/dashboard/src/components/adminLoadingAnimation/AdminLoadingAnimation.module.scss
src/dashboard/src/components/adminLoadingAnimation/AdminLoadingAnimation.tsx
src/dashboard/src/components/adminLoadingAnimation/index.ts
src/dashboard/src/components/charts/loadingAnimation/LoadingAnimation.module.scss
src/dashboard/src/components/index.ts
src/dashboard/src/components/pageLoadingAnimation/PageLoadingAnimation.module.scss
src/dashboard/src/components/pageLoadingAnimation/PageLoadingAnimation.tsx
src/dashboard/src/components/pageLoadingAnimation/index.ts

Added two new components for loading skeleton UI for dashboard pages and admin pages.
Refined styling for global loading state animation.
There are now three loading components:
- Global/individual chart loading component: components/chart/loadingAnimation
- Dashboard page skeleton UI loading component: components/pageLoadingAnimation
- Admin page skeleton UI loading component: components/adminLoadingAnimation

HOSTSD-257, 256 - loading ui for dashboard, admin pages

---

src/dashboard/src/components/dashboard/useDashboardFilter.ts
src/dashboard/src/components/filter/Filter.tsx

Fixed the reset filter button action.

HOSTSD-266 Fix dashboard filter

---

.github/workflows/ci-cd-dev.yml
.github/workflows/dotnet.yml
.github/workflows/nextjs.yml

Updating the various libraries for our CI/CD.

HOSTSD-248 Update github actions

---

src/dashboard/src/app/login/Login.module.scss
src/dashboard/src/components/charts/bar/allocationByVolume/AllocationByVolume.tsx
src/dashboard/src/components/charts/bar/smallBar/SmallBarChart.module.scss
src/dashboard/src/components/charts/doughnut/allOrganizations/AllOrganizations.module.scss
src/dashboard/src/components/charts/doughnut/totalStorage/TotalStorage.module.scss
src/dashboard/src/components/charts/line/LineChart.module.scss
src/dashboard/src/components/filter/Filter.module.scss
src/dashboard/src/components/pageLoadingAnimation/PageLoadingAnimation.module.scss
src/dashboard/src/styles/_variables.scss
src/dashboard/src/styles/globals.scss

Made panels on dashboard more flexible and responsive.  
Some panels aren't as flexible when resizing the window due to the Chart.js canvas setting widths when they load, but everything should display well at the time of first load.
Also made improvements to login page layout and overflow text in the small bar charts.

HOSTSD-272 - Optimize UI for smaller screens

---

devops/kustomize/base/data-service/cron-job.yaml
src/api/Areas/Dashboard/Controllers/ServerItemController.cs
src/dashboard/src/components/dashboard/Dashboard.tsx
src/dashboard/src/components/dashboard/useDashboardFilter.ts
src/dashboard/src/components/filter/Filter.tsx
src/dashboard/src/components/filter/FilteredOperatingSystemItems.tsx
src/dashboard/src/components/filter/FilteredOrganizations.tsx
src/dashboard/src/components/filter/FilteredServerItems.tsx
src/dashboard/src/components/filter/FilteredTenants.tsx
src/dashboard/src/hooks/data/useOperatingSystemItems.ts
src/data-service/DataService.cs
src/libs/dal/Services/FileSystemItemService.cs
src/libs/dal/Services/OrganizationService.cs
src/libs/dal/Services/ServerItemService.cs

Fixed issue with total storage formula.  Unable to test to confirm however due to ServiceNow API no longer returning data.
Fixed CronJob schedule issue.
Improved performance of filter bar to reduce round trips to the API.

HOSTSD-273 Fix total formula

---

devops/kustomize/base/api/deploy.yaml
devops/kustomize/overlays/dev/api/kustomization.yaml
devops/kustomize/overlays/test/api/kustomization.yaml
src/dashboard/src/components/dashboard/Dashboard.tsx
src/dashboard/src/components/filter/FilteredOperatingSystemItems.tsx
src/dashboard/src/components/filter/FilteredOrganizations.tsx
src/dashboard/src/components/filter/FilteredTenants.tsx

Fixing various dashboard state bugs.  Improving performance.

HOSTSD-273 Fixing bugs

---

devops/kustomize/base/app/deploy.yaml
src/api/Dockerfile

Resolving the issue where the user is kicked out after 5 minutes.

HOSTSD-277 Fix refresh token

---

src/dashboard/src/components/dashboard/Dashboard.tsx

Fixed issues related to changing the filter and dashboard values from a chart item.

HOSTSD-273 Fix dashboard

---

src/api/Areas/Admin/Controllers/UserController.cs
src/dashboard/src/app/client/admin/users/page.tsx
src/dashboard/src/app/page.tsx
src/dashboard/src/components/charts/allocationTable/TableRow.tsx
src/dashboard/src/components/charts/bar/allocationByStorageVolume/BarChart.tsx
src/dashboard/src/components/charts/bar/segmentedBarChart/useStorageTrendsData.ts
src/dashboard/src/components/charts/bar/smallBar/BarRow.tsx
src/dashboard/src/components/charts/doughnut/allOrganizations/utils/generateDoughnutChart.ts
src/dashboard/src/components/charts/doughnut/totalStorage/TotalStorage.tsx
src/dashboard/src/components/charts/doughnut/totalStorage/hooks/generateDoughnutChart.ts
src/dashboard/src/components/charts/storageTrends/useStorageTrendsData.ts
src/dashboard/src/components/dashboard/Dashboard.tsx
src/dashboard/src/utils/convertToStorageSize.ts
src/libs/dal/HSB.DAL.csproj
src/libs/dal/Services/FileSystemItemService.cs
src/libs/dal/Services/UserService.cs

Several bug fixes and changes.
- The API no longer convers the bytes to MB.  This is to resolve loss of precision when calculated.
- Client Organization Administrators can only add/update accordingly to their role limitations
- Single organization chart will now display the selected organization data

HOSTSD-246 Fix data

---

src/dashboard/src/components/charts/bar/segmentedBarChart/SegmentedBarChart.module.scss
src/dashboard/src/components/charts/storageTrends/StorageTrendsChart.module.scss

Adding back date picker buttons after hiding export to excel buttons

No ticket - Adding back date picker buttons after hiding export to excel buttons

---

src/dashboard/src/components/dashboard/Dashboard.tsx

Fixing issue when clicking operating systems, organizations, or servers within the dashboard.

HOSTSD-275 Fix dashboard

---

src/dashboard/src/components/charts/allocationTable/AllocationTable.module.scss
src/dashboard/src/components/charts/allocationTable/AllocationTable.tsx

For chart containing list of servers, added dropdown under search input that returns a clickable list of server names filtered by what is typed into the input.

HOSTSD-278 - Allocation Table - showing filtered list while searching

---

src/dashboard/src/app/style-guide/page.tsx
src/dashboard/src/components/filter/Filter.module.scss
src/dashboard/src/components/forms/select/FilterDropdown.tsx
src/dashboard/src/components/forms/select/Select.module.scss
src/dashboard/src/components/forms/select/index.ts

New component: FilterDropdown
This component has the ability to search/filter items in the custom dropdown.  Tried to reuse all logic contained in Select component.
All dropdowns in the Filter bar can be replaced with this dropdown, instead of using the 'select' dropdowns.
UI is finished, but work needs to be done to use this new component for Filter dropdowns: Tenant, Organization, Operating System, Server.

HOSTSD-299 - UI: Filter Dropdown

---

src/dashboard/src/components/charts/allocationTable/AllocationTable.module.scss
src/dashboard/src/components/charts/allocationTable/AllocationTable.tsx
src/dashboard/src/components/charts/allocationTable/TableRow.tsx

- Adding total used data to server tables.
- Updating styling
- For server links, adding scroll to top of page so server page doesn't render at bottom of page.

HOSTSD-271 - Adding total used to server chart

---

README.md
scripts/help.sh
src/data-service/DataService.cs

I believe I've fixed the issues related to servers not displaying their tenants.  This won't show up until tomorrow when the Data Service runs again.
Servers and File System Items that are uninstalled will now be deleted from HSB.  This will remove all history of these items, but I believe this makes the most sense with the present information.  Without removing them it will throw off all the total allocation calculations.
Also updated documentation related to CI/CD.

HOSTSD-246 Fix Data Service

---

src/dashboard/src/app/hsb/admin/users/AddNewUserRow.tsx
src/dashboard/src/app/hsb/admin/users/Users.module.scss
src/dashboard/src/app/hsb/admin/users/page.tsx
src/dashboard/src/components/table/Table.module.scss
src/dashboard/src/styles/_colors.scss

Adding a 'remove' button to remove rows added for new users on /admin/users page.

HOSTSD-302 - Admin: add ability to remove 'add new user' rows

---

EMERALD.md
src/api/Keycloak/CssHelper.cs
src/dashboard/src/app/api/auth/authOptions.ts
src/dashboard/src/app/hsb/admin/users/page.tsx
src/dashboard/src/app/login/page.tsx
src/dashboard/src/app/page.tsx
src/dashboard/src/app/welcome/Welcome.module.scss
src/dashboard/src/app/welcome/page.tsx
src/dashboard/src/components/auth/AuthState.tsx
src/dashboard/src/components/loadingAnimation/LoadingAnimation.module.scss
src/dashboard/src/store/useAppStore.ts
src/libs/dal/Extensions/ServiceCollectionExtensions.cs
src/libs/dal/Services/UserService.cs

Preapproved users will be able to login and receive their roles immediately without making a separate request for access.

HOSTSD-254 Add preapproved user

---

src/dashboard/src/components/charts/allocationTable/AllocationTable.module.scss
src/dashboard/src/components/charts/allocationTable/TableRow.tsx
src/dashboard/src/components/spinner/Spinner.module.scss

- Adjusting layout for server table - both with and without tenant column.
- Fixing loading spinner for 'update' button in filter bar

HOSTSD-307 - Fixing server table layout

---

README.md
src/api/Areas/Admin/Controllers/UserController.cs
src/api/Keycloak/CssHelper.cs
src/dashboard/src/components/auth/AuthState.tsx

Resolved an issue with user administration and optimistic concurrency.

Fix user admin

---

src/dashboard/src/app/hsb/admin/users/AddNewUserRow.tsx
src/dashboard/src/app/hsb/admin/users/Users.module.scss
src/dashboard/src/app/login/page.tsx
src/dashboard/src/app/welcome/page.tsx
src/dashboard/src/components/charts/doughnut/allOrganizations/AllOrganizations.module.scss
src/dashboard/src/components/charts/line/LineChart.module.scss
src/dashboard/src/components/charts/line/LineChart.tsx

- For Login and Welcome pages, updating the placeholder email to michael.tessier@gov.bc.ca, for users who want to request access or help with the dashboard.
- Also added disclaimer to the Storage Trends chart: "*Data shows totals on last available day of each month."
- Updated some styling: smaller button to remove new user row in admin view, alignment of all orgs chart info.

HOSTSD-312 - updating request access email and storage trends disclaimer

---

src/dashboard/src/app/not-authorized/NotAuthorized.module.scss
src/dashboard/src/app/not-authorized/page.tsx
src/dashboard/src/components/auth/AuthState.tsx
src/dashboard/src/components/header/Header.tsx

When a user account is disabled they will now be redirected to the Not Authorized page.

HOSTSD-254 Disable user account

---

src/dashboard/src/app/style-guide/page.tsx
src/dashboard/src/components/filter/FilteredOperatingSystemItems.tsx
src/dashboard/src/components/filter/FilteredOrganizations.tsx
src/dashboard/src/components/filter/FilteredServerItems.tsx
src/dashboard/src/components/filter/FilteredTenants.tsx

Replacing the current Select component with the new FilterDropdown component.

HOSTSD-300 Update filter select

---

devops/kustomize/base/data-service/config-map.yaml
devops/kustomize/base/data-service/cron-job.yaml
devops/kustomize/overlays/dev/data-service/kustomization.yaml
devops/kustomize/overlays/prod/data-service/kustomization.yaml
devops/kustomize/overlays/test/data-service/kustomization.yaml
src/data-service/Config/ServiceOptions.cs
src/data-service/DataService.cs

I have provided a way to configure the email subject so that it's obvious where the error is coming from.

Fix Data Service email

---

src/libs/dal/Services/ServerItemService.cs

Update api endpoint to resolve issue occurring in Data Service.

Fix Data Service

---

src/api/Areas/Admin/Controllers/OrganizationController.cs
src/api/Areas/Dashboard/Controllers/OrganizationController.cs

Removed caching as it was causing issues and it'll be too complex for now to update cache with the EF sql statements.

Fix organization admin

---

src/libs/Dockerfile

Update DB-Migration image to .NET8.0

Update DB-Migration image
